# Get users
GET http://localhost:5000/users

### -------------------------------------

# Add new user
POST http://localhost:5000/users/register
content-type: application/json

{
    "username": "drew{{$randomInt 00000 99999}}",
    "password": "password",
    "email": "email@email.com"
}

### -------------------------------------

# Login User
POST http://localhost:5000/users/login
content-type: application/json

{
    "username": "drew88400",
    "password": "password"
}

### -------------------------------------

# Make request with auth
GET http://localhost:5000/users/protected

